### ISSUE TITLE
Episode 5 TODO

### ISSUE THREAD

**Issue by msukkari** [gamedevmcgill/GDM-bootcamp-f2019#10]
- [x] add base code changes @Vassenx 

### Explanations
- [x]  Explain prefabs, taking into account Unity just updated their prefab format @msukkari 
- [ ] Explain the canvas @brendan-kellam

#### Michael
- [ ] Review episode 5 
#### Jack
- [ ] Review episode 5 
#### Brendan
- [ ] Review episode 5

### Merge
- [x] Merge code into master @msukkari
