### ISSUE TITLE
Episode 6 TODO

### ISSUE THREAD

**Issue by msukkari** [gamedevmcgill/GDM-bootcamp-f2019#11]
### Explanations
- [ ] Explain events and common uses
  - delegates and action syntax and briefly EventSystem
- [ ] Explain virtual keyword

#### Michael
- [ ] Review episode 6
#### Jack
- [ ] Review episode 6
#### Brendan
- [ ] Review episode 6

### Merge
- [x] Merge code into master @msukkari

**Comment by msukkari** [comment]
Regarding the events explanation, Jack already talked about this in ep4 explanations so I'm not sure if it's necessary to go over it again here

**Comment by msukkari** [comment]
Similarly to prev comment, I talked about virtual functions in ep2 explanations so I don't think we need to do it here again
