### ISSUE TITLE
Episode 7 TODO

### ISSUE THREAD

**Issue by msukkari** [gamedevmcgill/GDM-bootcamp-f2019#12]
### Base Code
- [x] Add in base code @Vassenx 

### Explanations
- [ ] Explain enums with example code @JackMinn 
- [ ] Explain debug mode @brendan-kellam 
https://docs.unity3d.com/Manual/InspectorOptions.html (this probs actually is good enough)
  - Be sure to mention: debugging with VS, when to use Debug.Log vs Debugger

#### Michael
- [ ] Review episode 7
#### Jack
- [ ] Review episode 7
#### Brendan
- [ ] Review episode 7

### Merge
- [x] Merge code into master @msukkari

**Comment by brendan-kellam** [comment]
@JackMinn Is the enum / example code explanation up on the repo?

**Comment by JackMinn** [comment]
@brendan-kellam no, not yet
