### ISSUE TITLE
Episode 8 TODO 

### ISSUE THREAD

**Issue by msukkari** [gamedevmcgill/GDM-bootcamp-f2019#13]
### Base Code
- [x] Add in base code @Vassenx 

### Explanations
- [x] Explain materials (TBD depth) @JackMinn 
- [ ]  TBD

### Code Changes
- [ ] Add in preset blend shapes and bones details (folder or zip)
- [x] TBD

### Review Task
Also research anything you don't know from this Integration video. Ex: meshfilter, skinnedMeshRenderer

#### Michael
- [ ] Review episode 8
#### Jack
- [ ] Review episode 8
#### Brendan
- [ ] Review episode 8

### Merge
- [x] Merge code into master @msukkari
