### ISSUE TITLE
Episode 1 TODO

### ISSUE THREAD

**Issue by msukkari** [gamedevmcgill/GDM-bootcamp-f2019#2]
### Explanations
- [x] Explain basic idea of what a scene, gameobject, and component is @msukkari 
- [x] Go over what the game loop is and some specific hook's Unity provides and how they relate to the game loop (start, awake, update, late update, etc) @msukkari 
- [x] Explain the basic idea of a ray and raycasting @msukkari 
- [x] Explain RigidBody and CharacterController (and their differences) @Vassenx 

### Code changes
- [x] Remove the WASD control changes @msukkari 

### Base code
- [x] Merge base code into master @Vassenx 

#### Sam
- [x] Review episode 1 explanations
#### Jack
- [ ] Review episode 1 explanations
#### Brendan
- [x] Review episode 1 explanations
