### ISSUE TITLE
Episode 4 TODO

### ISSUE THREAD

**Issue by msukkari** [gamedevmcgill/GDM-bootcamp-f2019#5]
### Explanations
- [x] introduce the singleton pattern (be sure to talk about pros and cons) @msukkari 
- [x] basics of delegates
- [x] talk about what ScriptableObj and MonoBehaviour are (linking to docs will be especially useful here)
